use_frameworks!

platform :ios, '10.0'

target 'LuckyUserDefaultsStorable_Example' do
  pod 'LuckyUserDefaultsStorable', :path => '../'

  target 'LuckyUserDefaultsStorable_Tests' do
    inherit! :search_paths

    
  end
end
